fix(): Refactor code for better readability and adherence to best pra…
solana-developers/movie-review-program-client pull request #1
Opened 2024-09-04 21:32 UTC by EmekaManuel

…ctices

- Replaced wildcard imports with specific imports for improved efficiency
- Added semicolons and ensured consistent formatting across the codebase
- Removed unnecessary IIFE wrappers and improved error handling
- Updated the initializeSignerKeypair, airdropSolIfNeeded, and sendTestMovieReview functions for better clarity
- Adjusted the main function to follow modern async patterns

2024-09-11 02:35 UTC, mikemaccana commented on src/index.ts
> +    return signer;
Use https://github.com/solana-developers/helpers?tab=readme-ov-file#add-a-new-keypair-to-an-env-file

2024-09-11 02:47 UTC, mikemaccana requested changes
There's one of the helpers that should be used here, will save our audience a bunch of time, see the comment above. Also note re: top level await below.

2024-09-11 02:47 UTC, mikemaccana commented on src/index.ts
> +  });
Avoid `.then()` - we use `esrun` and it supports top level `await` (see CONTRIBUTING).

2024-09-11 14:32 UTC, EmekaManuel commented on src/index.ts
> +  });
fixed ✅

2024-09-11 15:08 UTC, EmekaManuel commented on src/index.ts
> +    return signer;
I implemented this but on running the code, there seems to be a persistent error being thrown from the package `@solana-developers/helpers`. View my implementation and the error being thrown below. 

<img width="689" alt="Screenshot 2024-09-11 at 16 03 55" src="https://github.com/user-attachments/assets/ecd94ee0-27a8-4ca9-9240-1eaac16b45e0">
<img width="1002" alt="Screenshot 2024-09-11 at 16 04 22" src="https://github.com/user-attachments/assets/ef493944-88f1-432a-bfaf-4e53cdbc726b">

2024-09-12 20:45 UTC, mikemaccana requested changes
See comments above.

2024-09-12 20:45 UTC, mikemaccana commented on src/index.ts
> +    return signer;
We fixed an error in that module today - can you try https://www.npmjs.com/package/@solana-developers/helpers 2.5.5 and let me know?

2024-09-12 20:45 UTC, mikemaccana commented on src/index.ts
> +  }
Just use the helper. If the helper is broken, let's fix the helper rather than making a second copy of the same code.

2024-09-12 21:32 UTC, EmekaManuel commented on src/index.ts
> +  }
Implemented ✅

2024-09-12 21:33 UTC, EmekaManuel commented on src/index.ts
> +    return signer;
Hello Mike the new version worked perfectly now. Great job on the fix!

<img width="999" alt="Screenshot 2024-09-12 at 22 31 49" src="https://github.com/user-attachments/assets/43a12f9a-9d63-4e20-81ee-51ac271bd6a5">

2024-09-16 23:15 UTC, mikemaccana requested changes
See comment above.

2024-09-16 23:15 UTC, mikemaccana commented on src/index.ts
> +// }
Remove the dead code. See https://stackoverflow.com/questions/15699995/could-someone-explain-the-pros-of-deleting-or-keeping-unused-code

2024-09-16 23:16 UTC, mikemaccana commented on src/index.ts
> +// }
```suggestion
```

2024-09-16 23:17 UTC, merged